---
- name: Delete dns virtual machine
  hosts: localhost
  vars:
    - vm_name: dns
  tasks:
    - name: Delete vm data
      file:
        path: "/home/{{ ansible_user_id }}/.okd/vms/{{ vm_name }}"
        state: absent
    - name: Get vm info
      virt:
        command: info
        uri: "qemu:///session"
      register: info
    - debug:
        msg: "{{ info }}"
    - name: Destroy {{ vm_name }} vm
      virt:
        command: destroy
        name: "{{ vm_name }}"
        uri: "qemu:///session"
      when: info.dns is defined and info.dns.state == "running"
    - name: Undefine {{ vm_name }} vm
      virt:
        command: undefine
        name: "{{ vm_name }}"
        uri: "qemu:///session"
      when: info.dns is defined
    - name: Remove {{ vm_name }} vm host from known_hosts
      lineinfile:
        path: "/home/{{ ansible_user_id }}/.ssh/known_hosts"
        state: absent
        regexp: '^10\.0\.6\.10.*$'