---
- name: Install okd dns network
  hosts: localhost
  vars:
    network_name: okd-dns
  tasks:
    - name: Install {{ network_name }} network
      block:
        - name: Get networks defined
          virt_net:
            command: list_nets
          register: nets
        - name: Define {{ network_name }} network
          virt_net:
            command: define
            name: "{{ network_name }}"
            xml: '{{ lookup("template", "templates/network/okd-dns-network.xml.j2") }}'
          when: network_name|string not in nets.list_nets
        - name: Start {{ network_name }} network
          virt_net:
            command: start
            name: "{{ network_name }}"
          when: network_name|string not in nets.list_nets
        - name: Define {{ network_name }} network as autostart
          virt_net:
            autostart: yes
            name: "{{ network_name }}"
          when: network_name|string not in nets.list_nets
      become: true
      become_user: root