---
- name: This playbook deploy OKD 4 on a local server
  hosts: localhost
  tasks:
    - name: Add internal network
      include: add_internal_network.yml
    - name: Add fix bridge permissions for user
      include: add_fix_bridge_permissions_for_user.yml
    - name: Create dns virtual machine
      include: create_dns_vm.yml
    - name: Create container_registry okd virtual machine
      include: create_container_registry_vm.yml
    - name: Add okd cluster netword
      include: add_okd_cluster_network.yml
    - name: Create lb virtual machine
      include: create_load_balancer_vm.yml
    - name: Install prerequisite okd infrastructure
      include: install_prerequisite_okd_infrastructure.yml
    - name: Create bootstrap okd virtual machine
      include: create_bootstrap_okd_vm.yml
    - name: Create control planes virtual machines
      include: create_control_plane_okd_vm.yml
      with_items:
        - {index: 0, ip: '10.0.5.59', mac: '52:54:00:00:05:59'}
        - {index: 1, ip: '10.0.5.60', mac: '52:54:00:00:05:60'}
        - {index: 2, ip: '10.0.5.61', mac: '52:54:00:00:05:61'}

#- import_playbook: create_worker_0_okd_vm.yml
