---
- name: Uninstall okd cluster network
  hosts: localhost
  vars:
    network_name: okd-cluster
  tasks:
    - name: Uninstall {{ network_name }} network
      block:
        - name: Get networks defined
          virt_net:
            command: list_nets
          register: nets
        - name: Get {{ network_name }} info
          virt_net:
            command: status
            name: "{{ network_name }}"
          register: status
          when: network_name|string in nets.list_nets
        - name: Destroy {{ network_name }} network
          virt_net:
            command: destroy
            name: "{{ network_name }}"
          when: network_name|string in nets.list_nets and "active" == status.status
        - name: Undefine {{ network_name }} network
          virt_net:
            command: undefine
            name: "{{ network_name }}"
          when: network_name|string in nets.list_nets
      become: true
      become_user: root