---
- name: This playbook uninstall OKD 4 on a local server
  hosts: localhost
  tasks:
    - name: Delete odk dns network
      include: delete_okd_dns_network.yml
    - name: Remove fix bridge permissions for user
      include: remove_fix_bridge_permissions_for_user.yml
    - name: Delete dns virtual machine
      include: delete_dns_vm.yml
    - name: Delete container registry virtual machine
      include: delete_container_registry_vm.yml
    - name: Delete okd cluster network
      include: delete_okd_cluster_network.yml
    - name: Delete load balancer virtual machine
      include: delete_load_balancer_vm.yml
    - name: Uninstall prerequisite okd infrastructure
      include: uninstall_prerequisite_okd_infrastructure.yml
    - name: Delete bootstrap okd virtual machine
      include: delete_bootstrap_okd_vm.yml
    - name: Delete control planes virtual machine
      include: delete_control_plane_okd_vm.yml
      with_items:
        - {index: 0, ip: '10.0.5.59'}
        - {index: 1, ip: '10.0.5.60'}
        - {index: 2, ip: '10.0.5.61'}

#- import_playbook: delete_worker_0_okd_vm.yml
